name: ygg-starter
proxy:
  appserver:
    - ygg-starter.lndo.site
services: # Define your services
  appserver:  # Create a web server container
    type: php:7.3 # Specify what version of php to use
    via: apache   # This could be nginx, should you choose so
    webroot: public  # Specify webroot
    xdebug: false
    build_as_root:
      - apt-get update -y
      - apt install libxslt1-dev -y
      - docker-php-ext-install xsl
      - docker-php-ext-enable xsl
    run:
      - composer install
  database:
    type: mysql:5.7.24
    portforward: 3306
    healthcheck:
    creds:
      user: ygg
      password: ygg
      database: ygg
tooling:  # These toolings allow you to connect land <command> to the appropriate containers
  composer: # Call with "lando composer..."
    service: appserver
    description: Run composer commands in app
    cmd: composer --ansi
  php:      # Call with "lando php..."
    service: appserver
  artisan:      # Call with "lando php..."
    service: appserver
    cmd: php artisan
